#!/usr/bin/env fish
set -l options 'loops=?' 'fileFormat=?'
argparse $options -- $argv

if test -z "_flag_loops"
	set loops 1
else
	set loops $_flag_loops
end

# This is single threaded

# Get file list
set fileList (find -name \*.$_flag_fileFormat)

# Remove the "./"
set fileList (string trim --char="./" $fileList)

for file in $fileList	
	# Convert to 60 FPS
	ffmpeg -i $file -crf 10 -vf "minterpolate=fps=60:mi_mode=mci:mc_mode=aobmc:me_mode=bidir:vsbmc=1" $file.60fps.$_flag_fileFormat

	# Loop it
	ffmpeg -stream_loop $loops -i $file.60fps.$_flag_fileFormat -c copy $file.60fps.looped.$_flag_fileFormat
end