#!/usr/bin/env fish
# set -l options ""
# argparse $options -- $argv
   if ls ~/.dmmm-mouse-fix-pid > /dev/null 2>&1
      # Enable GNOME's hot corners
      dconf write /org/gnome/desktop/interface/enable-hot-corners true
      # Kill running watch
      kill -9 (cat ~/.dmmm-mouse-fix-pid)
      # Delete the file
      rm ~/.dmmm-mouse-fix-pid
   else
      # Disable GNOME's hot corners
      dconf write /org/gnome/desktop/interface/enable-hot-corners false
      # Control the mouse
      watch -n0 ydotool mousemove -a -x 384 -y 240 > /dev/null 2>&1 &
      # Register the PID of watch
      jobs -lp > ~/.dmmm-mouse-fix-pid
   end