#!/usr/bin/env fish
#TODO: Make it more elegant
set -l flags "complete" "user" "system" "switch"
argparse $flags -- $argv

# argv[0] -> action

switch "$argv[1]"
	case "update"
		if test -n "$_flag_complete"
			nixhm update --user
			nixhm update --system
		end

		if test -n "$_flag_user"
			#TODO: Turn this into an envvar
			cd $HOME/.config/home-manager
		end
		
		if test -n "$_flag_system"
			#TODO: Turn this into an envvar
			cd $HOME/Documents/Programming/Repositories/pearsche-nixos-setup
		end
		nix flake update
	case "upgrade"
		if test -n "$_flag_complete"
			nixhm upgrade --user
			nixhm upgrade --system "$_flag_switch"
		end

		if test -n "$_flag_user"
			home-manager switch
		end
		
		if test -n "$_flag_system"
			if test -n "$_flag_switch"
				sudo nixos-rebuild switch
			else
				sudo nixos-rebuild boot
			end
		end
end