#!/usr/bin/env fish
#TODO: Make it more elegant
set -l flags "complete" "switch"
argparse $flags -- $argv

# argv[1] -> action
# argv[2] -> level

switch "$argv[2]"
	case "user"
		set level user
		set flakeDirectory ~/.config/home-manager
		set upgradeCommand home-manager switch
	case "system"
		set level system
		set flakeDirectory /etc/nixos
		set upgradeCommand sudo nixos-rebuild
		if test -n "$_flag_switch"
			set upgradeCommand $upgradeCommand switch
		else
			set upgradeCommand $upgradeCommand boot
		end
	case "complete"
		nixhm $argv[1] user
		nixhm $argv[1] system
		exit 0
end

switch "$argv[1]"
	case "changelog"
		_nixhm_changelog $level

	case "update"
		cd $flakeDirectory
		nix flake update

	case "upgrade"
		$upgradeCommand
end
