#!/usr/bin/env fish
set -l options 'mode=?'
argparse $options -- $argv
set bootComplete (systemctl is-active graphical.target)
while test $bootComplete != "active"
	sleep 1
	set bootComplete (systemctl is-active graphical.target)
end

if test -n "$_flag_mode"
	if test "$_flag_mode" = "battery" -o "$_flag_mode" = "charger"
		switch $_flag_mode
			case battery
				set preference balance_power
			case charger
				set preference balance_performance
		end
		echo $preference | tee /sys/devices/system/cpu/cpufreq/policy?/energy_performance_preference
	else
		echo "You need to provide a proper mode for this script to actually do something, either --mode=charger or --mode=battery."
		return 1
	end
else
	echo "You need to provide a mode for this script to actually do something, either --mode=charger or --mode=battery."
	return 1
end