#!/usr/bin/env fish
set -l options 'value='
argparse $options -- $argv
set bootComplete (systemctl is-active graphical.target)
while test $bootComplete != "active"
	sleep 1
	set bootComplete (systemctl is-active graphical.target)
end

# value can be a number, or one of: power, balance-power, balance-performance, performance
echo $_flag_value | sudo tee /sys/devices/system/cpu/cpufreq/policy?/energy_performance_preference

