#!/usr/bin/env fish
	set -l options 'denoiseLevel=?' 'upscaleRatio=?' 'outputFormat=?'
	argparse $options -- $argv
	
	# Split inputFilename into two.
	# inputFilename[1] = just name
	# inputFilename[2] = extension
	# Use --right --max 1 to avoid splitting on anything that isnt the extension
	set inputFilename (string split --right --max 1 \. $argv[1])
	
	# first non-argparse'd argument is the input file, second is output file.
	# Remember to update the possible value ranges from time to time.
	
	# realesrgan doesn't have denoising. Future upscaler might have it so keep this just in case.
	#if test -z "$_flag_denoiseLevel"
	#	set _flag_denoiseLevel 1 # Middle level, [-1 to 1]
	#end

	if test -z "$_flag_upscaleRatio"
		set _flag_upscaleRatio 2 # User probably just wants to double size, [1 to 32, powers of 2]
	end
	
	if test -z "$_flag_outputFormat"
		set _flag_outputFormat png
	end

	realesrgan-ncnn-vulkan -n realesrgan-x4plus-anime -s $_flag_upscaleRatio -f $_flag_outputFormat -i $argv[1] -o $inputFilename[1].$_flag_outputFormat  # TODO: nihui/waifu2x-ncnn-vulkan#184
